#ifndef BASIC_ALGORITHM_GLOBAL_H
#define BASIC_ALGORITHM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASIC_ALGORITHM_LIBRARY)
#  define BASIC_ALGORITHMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASIC_ALGORITHMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASIC_ALGORITHM_GLOBAL_H
